enum STRINGS {
  selectDeparture = 'Select departure city',
  selectArrival = 'Select arrival city',
  search = 'Search',
  from = 'From',
  to = 'To',
  sortBy = 'Sort By',
  filterBy = 'Filter By',
  fare = 'Fare',
  duration = 'Duration',
  nonStopFlight = 'Non stop flight',
  singleStopFlight = 'One stop flight',
  selectSeats = 'Select seats',
  selectedSeat = 'Selected Seat',
  selectedSeats = 'Selected Seats',
  dashSymbol = '--',
  ellipsisSymbol = '...',
  rupeeSymbol = '₹',
  bookTicket = 'Book Ticket',
  noFlightsFound = 'No Flights Found',
  bookFlight = 'Book Flight',
  bookings = 'Bookings',
  bookedSeats = 'Booked Seats',
  totalFare = 'Total Fare',
  bookedDate = 'Booked Date',
  terminalNumber = 'Departure Terminal number',
  airportName = 'Airport name',
  selectDate = 'Select Date',
  apply = 'Apply',
  cancel = 'Cancel',
  select = 'Select',
  enterValidCityCode = 'Please enter valid city code',
  selectCity = 'Select city',
}

export default STRINGS;
