enum STRINGS {
  enterSource = 'Enter Source',
  enterDestination = 'Enter Destination',
  search = 'Search',
  from = 'From',
  to = 'To',
  sortBy = 'Sort By',
  filterBy = 'Filter By',
  fare = 'Fare',
  duration = 'Duration',
  nonStopFlight = 'Non stop flight',
  singleStopFlight = 'One stop flight',
  selectSeats = 'Select seats',
  selectedSeat = 'Selected Seat',
  selectedSeats = 'Selected Seats',
  dashSymbol = '--',
  ellipsisSymbol = '...',
  rupeeSymbol = '₹',
  bookTicket = 'Book Ticket',
  noFlightsFound = 'No Flights Found',
  modifySearchAndTryAgain = 'Please modify your search and try again',
  bookFlight = 'Book Flight',
  bookings = 'Bookings',
  bookedSeats = 'Booked Seats',
  totalFare = 'Total Fare',
  bookedDate = 'Booked Date',
  terminalNumber = 'Departure Terminal number',
  airportName = 'Airport name',
}

export default STRINGS;
